=== limburgie/php-movico/php-movico/lib/component/dtd/view.dtd
<!ELEMENT view ANY>

<!ELEMENT form ANY>

<!ELEMENT css EMPTY>
<!ATTLIST css src CDATA #REQUIRED>

<!ELEMENT js EMPTY>
<!ATTLIST js src CDATA #REQUIRED>

<!ELEMENT commandButton EMPTY>
<!ATTLIST commandButton
	value CDATA #REQUIRED
	action CDATA #REQUIRED
>

<!ELEMENT inputSecret EMPTY>
<!ATTLIST inputText 
	value CDATA #REQUIRED
	id CDATA #IMPLIED
>

<!ELEMENT inputText EMPTY>
<!ATTLIST inputText
	value CDATA #REQUIRED
	id CDATA #IMPLIED
>

<!ELEMENT inputTextArea EMPTY>
<!ATTLIST inputTextArea
	value CDATA #REQUIRED
	id CDATA #IMPLIED
>

<!ELEMENT outputLabel EMPTY>
<!ATTLIST outputLabel
	value CDATA #REQUIRED
	for CDATA #REQUIRED
>

<!ELEMENT outputText EMPTY>
<!ATTLIST outputText value CDATA #REQUIRED>

<!ELEMENT selectOneMenu EMPTY>
<!ATTLIST selectOneMenu
	options CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ELEMENT panelGrid ANY>
<!ATTLIST panelGrid 
	columns CDATA #REQUIRED
>

<!ELEMENT dataTable (column*)>
<!ATTLIST dataTable
	value CDATA #REQUIRED
	var CDATA #REQUIRED
>

<!ELEMENT column ANY>

<!ELEMENT colHeader ANY>

=== limburgie/php-movico/php-movico/view/index.xml
<?xml version="1.0"?>
<!DOCTYPE view SYSTEM "../lib/component/dtd/view.dtd">
<view title="Overzicht Gebruikers">
	<css src="test.css"/>
	<message/>
	<form>
		<dataTable value="#{UserBean.users}" var="user" rendered="#{UserBean.hasUsers}">
			<column>
				<colHeader>
					<outputText value="Creatie"/>
				</colHeader>
				<outputText value="#{user.createDate}"/>
			</column>
			<column>
				<colHeader>
					<outputText value="Naam"/>
				</colHeader>
				<outputText value="#{user.fullName}"/>
			</column>
			<column>
				<colHeader>
					<outputText value="Default?"/>
				</colHeader>
				<outputText value="#{user.default}"/>
			</column>
			<column>
				<colHeader>
					<outputText value="Actions"/>
				</colHeader>
				<commandButton action="#{UserBean.edit}" value="Aanpassen"/>
				<commandButton action="#{UserBean.delete}" value="Verwijderen" popup="Ben je zeker dat je #{user.firstName} wil verwijderen?"/>
			</column>
		</dataTable>
		<commandButton action="#{UserBean.create}" value="Nieuw"/>
		<ajaxLoading/>
	</form>
</view>

=== limburgie/php-movico/php-movico/view/view1.xml
<?xml version="1.0"?>
<!DOCTYPE note SYSTEM "../lib/dtd/view.dtd">
<view>
	<css src="test.css"/>
    <outputText value="HelloBean_message"/>
    <form>
    	<selectOneMenu options="HelloBean_names" value="HelloBean_name"/>
        <commandLink action="HelloBean_sayHello" value="Say Hello!"/>
        <dataTable var="test" value="HelloBean_bla_cool">
        	<column>
        		<header>
        			Blabla
        		</header>
        		<inputText value="HelloBean_test"/>
        	</column>
        </dataTable>
    </form>
</view>

=== limburgie/php-movico/php-movico/view/view2.xml
<?xml version="1.0"?>
<!DOCTYPE view SYSTEM "../lib/component/dtd/view.dtd">
<view>
	<dataTable var="user" value="HelloBean.users">
		<column>
			<colHeader>
				<outputText value="Voornaam"/>
			</colHeader>
			<outputText value="user.firstName"/>
		</column>
		<column>
			<colHeader>
				<outputText value="Achternaam"/>
			</colHeader>
			<outputText value="user.lastName"/>
		</column>
		<column>
			<commandButton action="HelloBean.edit" value="Edit"/>
		</column>
	</dataTable>
</view>
