=== limburgie/php-movico/php-movico/lib/servicebuilder/dtd/service.dtd
<!ELEMENT service-builder (entity+, order?, finder*)>

<!ELEMENT entity (column*,finder*,order?)>
<!ATTLIST entity
	name CDATA #REQUIRED
	table CDATA #IMPLIED
>

<!ELEMENT column EMPTY>
<!ATTLIST column
	name CDATA #REQUIRED
	type (String|int|boolean|Date|Collection) #REQUIRED
	primary CDATA #IMPLIED
	auto-increment CDATA #IMPLIED
	size CDATA #IMPLIED
	entity CDATA #IMPLIED
	mapping-key CDATA #IMPLIED
>

<!ELEMENT order (order-column+)>

<!ELEMENT order-column EMPTY>
<!ATTLIST order-column
	name CDATA #REQUIRED
	order-by CDATA #REQUIRED
>

<!ELEMENT finder (finder-column+)>
<!ATTLIST finder
	name CDATA #REQUIRED
	unique CDATA #IMPLIED
>

<!ELEMENT finder-column EMPTY>
<!ATTLIST finder-column
	name CDATA #REQUIRED
	comparator CDATA #IMPLIED
>

=== limburgie/php-movico/php-movico/config/service.xml
<?xml version="1.0"?>
<!DOCTYPE service-builder SYSTEM "../lib/servicebuilder/dtd/service.dtd">
<service-builder>
	<entity name="User" table="movico_user">
		<column name="id" type="int" primary="true" auto-increment="true"/>
		<column name="firstName" type="String" size="25"/>
		<column name="lastName" type="String" size="25"/>
		<column name="createDate" type="Date"/>
		<column name="default" type="boolean"/>
	</entity>
	
	<!-- 1 to N relationship -->
	<entity name="Team" table="movico_team">
		<column name="teamId" type="int" primary="true" auto-increment="true"/>
		<column name="name" type="String" size="25"/>
		<column name="players" type="Collection" entity="Player"/>
	</entity>
	<entity name="Player" table="movico_player">
		<column name="playerId" type="int" primary="true" auto-increment="true"/>
		<column name="name" type="String" size="25"/>
	</entity>
	
	<!-- M to N relationship -->
	<entity name="Student" table="movico_student">
		<column name="studentId" type="int" primary="true" auto-increment="true"/>
		<column name="name" type="String" size="25"/>
		<column name="teachers" type="Collection" entity="Teacher" mapping-table="movico_students_teachers"/>
	</entity>
	<entity name="Teacher" table="movico_teacher">
		<column name="teacherId" type="int" primary="true" auto-increment="true"/>
		<column name="name" type="String" size="25"/>
		<column name="students" type="Collection" entity="Student" mapping-table="movico_students_teachers"/>
		<order>
			<order-column name="name" order-by="asc"/>
		</order>
	</entity>
	
	<!-- Boggle -->
	<entity name="BoggleHighScore" table="movico_boggle_hscore">
		<column name="hscoreId" type="int" primary="true" auto-increment="true"/>
		<column name="name" type="String" size="25"/>
		<column name="points" type="int"/>
		<column name="playDate" type="Date"/>
		<order>
			<order-column name="points" order-by="desc"/>
		</order>
	</entity>
	<entity name="BoggleGame" table="boggle_game">
		<column name="gameId" type="int" primary="true" auto-increment="true"/>
		<column name="started" type="boolean"/>
		<column name="players" type="Collection" entity="BogglePlayer" mapping-key="gameId"/>
		<finder name="Started">
			<finder-column name="started"/>
		</finder>
	</entity>
	<entity name="BogglePlayer" table="boggle_player">
		<column name="playerId" type="int" primary="true" auto-increment="true"/>
		<column name="name" type="String" size="25"/>
		<finder name="Name" unique="true">
			<finder-column name="name"/>
		</finder>
	</entity>
	<entity name="BoggleGuessedWord" table="boggle_guessed_word">
		<column name="wordId" type="int" primary="true" auto-increment="true"/>
		<column name="word" type="String" size="16"/>
		<column name="gameId" type="int"/>
		<column name="playerId" type="int"/>
	</entity>
</service-builder>
