=== limburgie/php-movico/php-movico/dtd/view.dtd
<!ELEMENT view ANY>

<!ELEMENT form ANY>

<!ELEMENT commandButton EMPTY>
<!ATTLIST commandButton value CDATA #REQUIRED>
<!ATTLIST commandButton action CDATA #REQUIRED>

<!ELEMENT inputSecret EMPTY>
<!ATTLIST inputText value CDATA #REQUIRED>
<!ATTLIST inputText id CDATA #IMPLIED>

<!ELEMENT inputText EMPTY>
<!ATTLIST inputText value CDATA #REQUIRED>
<!ATTLIST inputText id CDATA #IMPLIED>

<!ELEMENT inputTextArea EMPTY>
<!ATTLIST inputTextArea value CDATA #REQUIRED>
<!ATTLIST inputTextArea id CDATA #IMPLIED>

<!ELEMENT outputLabel EMPTY>
<!ATTLIST outputLabel value CDATA #REQUIRED>
<!ATTLIST outputLabel for CDATA #REQUIRED>

<!ELEMENT outputText EMPTY>
<!ATTLIST outputText value CDATA #REQUIRED>

<!ELEMENT panelGrid ANY>
<!ATTLIST panelGrid columns CDATA #REQUIRED>

=== limburgie/php-movico/php-movico/view/view.xml
<?xml version="1.0"?>
<!DOCTYPE note SYSTEM "../dtd/view.dtd">
<view>
	<outputText value="HelloBean_message"/>
	<form>
		<panelGrid columns="2">
			<outputLabel for="name" value="Naam: "/>
			<inputText id="name" value="HelloBean_name"/>
			
			<outputLabel value="Reactie: " for="comments"/>
			<inputTextArea id="comments" value="HelloBean_comments"/>
			
			<commandButton action="HelloBean_sayHello" value="Say Hello!"/>
		</panelGrid>
	</form>
</view>
